apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apache.fullname" . }}
  labels:
    {{- include "apache.labels" . | nindent 4 }}
    {{- include "apache.play" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apache.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "apache.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/local/apache2/share/sam
              name: mounting
            - mountPath: /config/passwds
              name: config
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom: 
            - configMapRef:
                name: example-configmap
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: mounting
          persistentVolumeClaim: 
            claimName: pvclaim
        - name: config
          configMap:
            name: example-configmap
