apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-06f4aae24cc8de4be
    fsType: ext4
