version: '3'
    
services:
  jenkins:
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - /maven:/maven
      - /java:/java
      - /jenkins:/var/jenkins_home
      
