{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "node-exporter.serviceAccountName" . }}
  labels:
{{ include "node-exporter.labels" . | indent 4 }}
{{- end -}}
