{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "deploys.serviceAccountName" . }}
  labels:
{{ include "deploys.labels" . | indent 4 }}
{{- end -}}
