apiVersion: v1
kind: Pod
metadata:
  name: apps
  labels: 
    author: praveen
spec:
  containers:
    - name: httpd
      image: httpd
      ports: 
      - containerPort: 80
    - name: httpd1
      image: httpd
      ports: 
      - containerPort: 80

